const fs = require('fs');
const path = require('path');

const SOURCE_DIR = path.join(__dirname, 'result2');

// China Exams
const chinaExam = [
  {
    id: 'cet4',
    name: 'CET-4',
    description: 'College English Test Band 4 Vocabulary',
    category: 'China Exams',
    tags: ['College English'],
    url: '/dicts/CET4_T.json',
    length: 2607,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'cet6',
    name: 'CET-6',
    description: 'College English Test Band 6 Vocabulary',
    category: 'China Exams',
    tags: ['College English'],
    url: '/dicts/CET6_T.json',
    length: 2345,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'xinghuoqiaoji_4',
    name: 'Band 4 Quick Memorization',
    description: 'Band 4 Quick Memorization',
    category: 'China Exams',
    tags: ['College English'],
    url: '/dicts/xinghuoqiaoji_4.json',
    length: 2522,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'xinghuoqiaoji_6',
    name: 'Band 6 Quick Memorization',
    description: 'Band 6 Quick Memorization',
    category: 'China Exams',
    tags: ['College English'],
    url: '/dicts/xinghuoqiaoji_6.json',
    length: 7520,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'cet4-sub',
    name: 'CET-4-Sub',
    description: 'Vocabulary Subtraction - Band 4',
    category: 'China Exams',
    tags: ['College English'],
    url: '/dicts/DanCiDeJianFa_4.json',
    length: 1957,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'cet6-sub',
    name: 'CET-6-Sub',
    description: 'Vocabulary Subtraction - Band 6',
    category: 'China Exams',
    tags: ['College English'],
    url: '/dicts/DanCiDeJianFa_6.json',
    length: 1949,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyan',
    name: 'Postgraduate Entrance Exam',
    description: 'Postgraduate English Entrance Exam Vocabulary',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/KaoYan_3_T.json',
    length: 3728,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyan_2024',
    name: 'Postgraduate Exam 2024',
    description: 'Postgraduate English Entrance Exam Vocabulary 2024',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/KaoYan_2024.json',
    length: 3731,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyanshanguo_2023',
    name: 'Postgraduate Exam Flash 2023',
    description: 'High, Medium, and Low Frequency Words 2023',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/KaoYanShanGuo_2023.json',
    length: 1771,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '926',
    name: 'Postgraduate Exam 926 Vocabulary',
    description: '926 Core Vocabulary',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/926.json',
    length: 926,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'dancimimi_1',
    name: 'Secret of Words - English 1',
    description: 'Secret of Words English (1)',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/DanCiDeMimi_1.json',
    length: 5657,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'dancimimi_2',
    name: 'Secret of Words - English 2',
    description: 'Secret of Words English (2)',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/DanCiDeMimi_2.json',
    length: 3827,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '2024HongBao T1',
    name: '2024 Postgraduate English Hongbaoshu (Part 1)',
    description: '2024 Postgraduate English Hongbaoshu Essential Words (Part 1)',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/2024HongBao_T1.json',
    length: 997,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '2024HongBao T2',
    name: '2024 Postgraduate English Hongbaoshu (Part 2)',
    description: '2024 Postgraduate English Hongbaoshu Essential Words (Part 2)',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/2024HongBao_T2.json',
    length: 854,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'hongbaoshu-2026',
    name: '2026 Postgraduate English Hongbaoshu',
    description: '2026 Postgraduate Vocabulary (Essential + Basic + Advanced Words)',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/hongbaoshu-2026.json',
    length: 4858,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'English_II',
    name: 'English II Word Book',
    description: 'Postgraduate English II Word Book',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/English_II.json',
    length: 4559,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyanshanguo2025',
    name: 'Postgraduate Shanguo 2025',
    description: 'Postgraduate Shanguo 2025',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/kaoyanshanguo2025.json',
    length: 2257,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'level4',
    name: 'TEM-4',
    description: 'Test for English Majors Band 4 Vocabulary',
    category: 'China Exams',
    tags: ['College English'],
    url: '/dicts/Level4luan_2_T.json',
    length: 4025,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'level8',
    name: 'TEM-8',
    description: 'Test for English Majors Band 8 Vocabulary',
    category: 'China Exams',
    tags: ['College English'],
    url: '/dicts/Level8luan_2_T.json',
    length: 12197,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'pets3',
    name: 'PETS',
    description: 'National English Level Test Frequently Tested Vocabulary',
    category: 'China Exams',
    tags: ['PET'],
    url: '/dicts/PETS_3.json',
    length: 1942,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'pets3-2023',
    name: 'PETS-2023',
    description: 'National English Level Test Frequently Tested Vocabulary',
    category: 'China Exams',
    tags: ['PET'],
    url: '/dicts/PETS3-2023.json',
    length: 4449,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'self-study_English1',
    name: 'Self-study Exam 1800 High-Frequency Words',
    description: 'Self-study Exam 1800 High-Frequency Words',
    category: 'China Exams',
    tags: ['Self-study English II'],
    url: '/dicts/self-study_English1.json',
    length: 1800,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'self-study_English2',
    name: 'Self-study English II High-Frequency YouYou Words',
    description: 'Self-study English II High-Frequency YouYou Words',
    category: 'China Exams',
    tags: ['Self-study English II'],
    url: '/dicts/self-study_English2.json',
    length: 2181,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'self-study_English3',
    name: 'Self-study English II Complete Word List',
    description: '00015 Self-study English II Complete Word Book',
    category: 'China Exams',
    tags: ['Self-study English II'],
    url: '/dicts/self-study_English3.json',
    length: 4603,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'coca_20000',
    name: 'COCA20000 Words',
    description: 'COCA20000 Words',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/coca20000.json',
    length: 20199,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '4000_Essential_English_Words1',
    name: 'Essential Words',
    description: '4000 Essential English Words meaning',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/4000_Essential_English_Words-meaning.json',
    length: 3600,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '4000_Essential_English_Words2',
    name: 'Essential Words',
    description: '4000 Essential English Words sentence',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/4000_Essential_English_Words-sentence.json',
    length: 3600,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'longman_communication_3000_words',
    name: 'Longman Communication 3000',
    description: 'Most frequent words in both spoken and written English',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/Longman_Communication_3000.json',
    length: 3168,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_2000_English_Words',
    name: 'Top 2000 words',
    description: 'with highest frequency',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/top2000words.json',
    length: 1867,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_1500_nouns_Words',
    name: 'Top 1500 Nouns',
    description: 'with highest frequency',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/Top1500NounWords.json',
    length: 1525,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_1000_verb_Words',
    name: 'Top 1000 Verbs',
    description: 'with highest frequency',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/Top1000VerbWords.json',
    length: 1011,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_500_Adj_Words',
    name: 'Top 500 adj.',
    description: 'with highest frequency',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/Top500AdjectiveWords.json',
    length: 527,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_250_Adv_Words',
    name: 'Top 250 adv.',
    description: 'with highest frequency',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/Top250AdverbWords.json',
    length: 255,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_60_Pronouns',
    name: 'Top 60 pron.',
    description: 'with highest frequency',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/Top60Pronouns.json',
    length: 59,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_50_Prepositions',
    name: 'Top 50 prep.',
    description: 'with highest frequency',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/Top50Prepositions.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'suffix word',
    name: 'suffix word',
    description: 'common suffix',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/suffix_word.json',
    length: 126,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'word roots1',
    name: 'word roots1',
    description: 'common roots',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/word_roots1.json',
    length: 369,
    language: 'en',
    languageCategory: 'en',
  },

  {
    id: 'adult self-study examination',
    name: 'Adult College Entrance Exam Vocabulary',
    description: 'Adult College Entrance Exam Vocabulary',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/adult-self-study-examination.json',
    length: 3692,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'zhuan-cha-ben-ying-yu',
    name: 'Special Insertion Bachelor English Vocabulary',
    description: 'Special Insertion Bachelor English Vocabulary',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/zhuan-cha-ben.json',
    length: 3216,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'zhuan-sheng-ben-xue-shi',
    name: 'Bachelor\'s Degree English for Adult College Entrance Exam',
    description: 'Bachelor\'s Degree English for Adult College Entrance Exam',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/xueshiyingyu.json',
    length: 897,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Oxford5000',
    name: 'Oxford 5000 Words',
    description: 'Oxford 5000 Words',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/Oxford5000.json',
    length: 5836,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Merriam_Webster_sVocabularyBuilder',
    name: 'Merriam-Webster\'s Vocabulary Builder',
    description: 'Merriam-Webster\'s Vocabulary Builder',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/Merriam_Webster_sVocabularyBuilder.json',
    length: 1191,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'tingshuokaoshi',
    name: 'Listening and Speaking Test Common Vocabulary',
    description: 'Common vocabulary for 16 scenarios in listening and speaking tests',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/tingshuokaoshi.json',
    length: 556,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'TOEFL_ZhangHongYan',
    name: 'ZhangHongYan\'s TOEFL Vocabulary Book',
    description: 'ZhangHongYan\'s TOEFL Vocabulary Book - Words Categorized',
    category: 'International Exams',
    tags: ['TOEFL'],
    url: '/dicts/TOEFL_ZhangHongYan.json',
    length: 4032,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '2025KaoYanHongBaoShu',
    name: '2025 Postgraduate English Vocabulary Hongbao Book',
    description: '2025 Postgraduate English Vocabulary Hongbao Book',
    category: 'China Exams',
    tags: ['Postgraduate Exam'],
    url: '/dicts/2025KaoYanHongBaoShu.json',
    length: 6705,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '3000_ClassRoom_English_Words',
    name: 'Adult College Entrance Exam 3000 Words',
    description: 'Adult College Entrance Exam Vocabulary',
    category: 'China Exams',
    tags: ['College English'],
    url: '/dicts/3000_ClassRoom_English_Words.json',
    length: 2991,
    language: 'en',
    languageCategory: 'en',
  },

  {
    id: 'frequently_used_words01',
    name: 'High-Frequency Words Level 1',
    description: 'High-Frequency Words Level 1',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/frequently_used_word01.json',
    length: 679,
    language: 'en',
    languageCategory: 'en',
  },

  {
    id: 'frequently_used_words03',
    name: 'High-Frequency Words Level 2',
    description: 'High-Frequency Words Level 2',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/frequently_used_word02.json',
    length: 1040,
    language: 'en',
    languageCategory: 'en',
  },

  {
    id: 'frequently_used_words03',
    name: 'High-Frequency Words Level 3',
    description: 'High-Frequency Words Level 3',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/frequently_used_word03.json',
    length: 1435,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Macmillan7000',
    name: 'Macmillan 7000',
    description: 'Macmillan 7000',
    category: 'China Exams',
    tags: ['Others'],
    url: '/dicts/Macmillan7000.json',
    length: 6268,
    language: 'en',
    languageCategory: 'en',
  },
]

// International Exams
const internationalExam = [
  {
    id: 'pet-2024',
    name: 'PET-2024',
    description: 'Cambridge English - 2024',
    category: 'International Exams',
    tags: ['PET'],
    url: '/dicts/pet-vacabulary-list-2024.json',
    length: 1871,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gmat',
    name: 'GMAT',
    description: 'GMAT Vocabulary',
    category: 'International Exams',
    tags: ['GMAT'],
    url: '/dicts/GMAT_3_T.json',
    length: 3047,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre',
    name: 'GRE',
    description: 'GRE Vocabulary',
    category: 'International Exams',
    tags: ['GRE'],
    url: '/dicts/GRE_3_T.json',
    length: 6515,
    language: 'en',
    languageCategory: 'en',
  },
    {
    id: 'gre1500',
    name: 'GRE Key 1500 Words - Brother Fen',
    description: 'GRE & TEM-8 Overlapping High-Frequency Vocabulary',
    category: 'International Exams',
    tags: ['GRE'],
    url: '/dicts/GRE_1500.json',
    length: 1533,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre3000',
    name: 'GRE3000',
    description: 'GRE3000 Vocabulary',
    category: 'International Exams',
    tags: ['GRE'],
    url: '/dicts/GRE3000_3_T.json',
    length: 3041,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE-computer-based-test',
    name: 'GRE Computer-Based Test Vocabulary',
    description: 'GRE Computer-Based Test Vocabulary',
    category: 'International Exams',
    tags: ['GRE'],
    url: '/dicts/GRE-computer-based-test.json',
    length: 1451,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ZaiYaoNiMing_GRE3000',
    name: 'GRE3000 - Another Life',
    description: 'GRE3000 Vocabulary - New Version with Parts of Speech',
    category: 'International Exams',
    tags: ['GRE'],
    url: '/dicts/ZaiYaoNiMing_GRE3000.json',
    length: 3041,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE_equivalent',
    name: 'GRE Equivalent Words',
    description: 'GRE Equivalent Words',
    category: 'International Exams',
    tags: ['GRE'],
    url: '/dicts/GRE_equivalent.json',
    length: 827,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE_ciyileiji',
    name: 'GRE Words Categorized',
    description: 'GRE Words Categorized',
    category: 'International Exams',
    tags: ['GRE'],
    url: '/dicts/gre-ciyileiji.json',
    length: 8785,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS_tinglichangjing',
    name: 'IELTS Listening Scenario Vocabulary',
    description: 'IELTS Listening Scenario Vocabulary',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS_tinglichangjing.json',
    length: 1204,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts_disorder',
    name: 'IELTS Random Order Complete Version',
    description: 'IELTS Random Order Complete Version',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS_disorder.json',
    length: 9389,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts_order',
    name: 'IELTS Sequential Order Complete Version',
    description: 'IELTS Sequential Order Complete Version',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS_order.json',
    length: 9389,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts',
    name: 'IELTS',
    description: 'IELTS Vocabulary',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS_3_T.json',
    length: 3575,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'heqiong',
    name: 'HeQiong IELTS Listening Essential Vocabulary',
    description: 'Comprehensive Test',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/HeQiong_IELTS.json',
    length: 2529,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang3',
    name: 'IELTS Wang C3',
    description: 'IELTS Listening Proper Noun Corpus',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_3.json',
    length: 1135,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang4',
    name: 'IELTS Wang C4',
    description: 'IELTS Listening Adjective/Adverb Corpus',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_4.json',
    length: 346,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang5',
    name: 'IELTS Wang C5',
    description: 'Elision & Liaison Mixed Training Corpus',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_5.json',
    length: 1569,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang11',
    name: 'IELTS Wang C11',
    description: 'Comprehensive Test',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_11.json',
    length: 1738,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'DuckCircle_IELTS',
    name: 'Duck Circle IELTS Core Words',
    description: 'Duck Circle IELTS Core Words',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/DuckCircle_IELTS.json',
    length: 2644,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSVocabularyBible',
    name: 'IELTS Vocabulary Bible',
    description: 'IELTS Vocabulary Bible',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTSVocabularyBible.json',
    length: 3673,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-807',
    name: 'IELTS Wanglu 807',
    description: 'IELTS Wanglu 807',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/ielts-807.json',
    length: 4340,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-high',
    name: 'IELTS Real Vocabulary High Frequency',
    description: 'IELTS Real Vocabulary (High Frequency Words)',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-high.json',
    length: 524,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-5',
    name: 'IELTS Real Vocabulary 5',
    description: 'IELTS Real Vocabulary (5 Frequency Words & Variable Frequency)',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-5.json',
    length: 183,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-4',
    name: 'IELTS Real Vocabulary 4',
    description: 'IELTS Real Vocabulary (4 Frequency Words & Variable Frequency)',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-4.json',
    length: 201,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-3',
    name: 'IELTS Real Vocabulary 3',
    description: 'IELTS Real Vocabulary (3 Frequency Words & Variable Frequency)',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-3.json',
    length: 256,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-2',
    name: 'IELTS Real Vocabulary 2',
    description: 'IELTS Real Vocabulary (2 Frequency Words & Variable Frequency)',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-2.json',
    length: 402,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-1',
    name: 'IELTS Real Vocabulary 1',
    description: 'IELTS Real Vocabulary (1 Frequency Words & Variable Frequency)',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-1.json',
    length: 737,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS9988wangyong',
    name: 'IELTS 9988 Wangyong',
    description: 'IELTS 9988 Wangyong',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS9988wangyong.json',
    length: 3698,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSKingLu807',
    name: 'Wanglu 807 IELTS Vocabulary Listening 2nd Edition',
    description: 'Wanglu 807 IELTS Vocabulary Listening 2nd Edition',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTSKingLu807.json',
    length: 1916,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSXDF7000',
    name: '7000 IELTS Words Memorized in 100 Sentences',
    description: 'XDF Vocabulary List: 7000 IELTS Words Memorized in 100 Sentences',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS_XDF_7000.json',
    length: 5567,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-oral-900',
    name: 'IELTS Speaking 900 Beta',
    description: '900 IELTS Speaking Sentences, requires smaller English font size in QWERTY settings',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-oral-900.json',
    length: 900,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task1',
    name: 'XDF Listening IELTS Intermediate Direct Day1',
    description: 'XDF Listening IELTS Intermediate Direct Day1',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task1.json',
    length: 44,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task2',
    name: 'XDF Listening IELTS Intermediate Direct Day2',
    description: 'XDF Listening IELTS Intermediate Direct Day2',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task2.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task3',
    name: 'XDF Listening IELTS Intermediate Direct Day3',
    description: 'XDF Listening IELTS Intermediate Direct Day3',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task3.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task4',
    name: 'XDF Listening IELTS Intermediate Direct Day4',
    description: 'XDF Listening IELTS Intermediate Direct Day4',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task4.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task5',
    name: 'XDF Listening IELTS Intermediate Direct Day5',
    description: 'XDF Listening IELTS Intermediate Direct Day5',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task5.json',
    length: 38,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task6',
    name: 'XDF Listening IELTS Intermediate Direct Day6',
    description: 'XDF Listening IELTS Intermediate Direct Day6',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task6.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task7',
    name: 'XDF Listening IELTS Intermediate Direct Day7',
    description: 'XDF Listening IELTS Intermediate Direct Day7',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task7.json',
    length: 39,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task8',
    name: 'XDF Listening IELTS Intermediate Direct Day8',
    description: 'XDF Listening IELTS Intermediate Direct Day8',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task8.json',
    length: 32,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task9',
    name: 'XDF Listening IELTS Intermediate Direct Day9',
    description: 'XDF Listening IELTS Intermediate Direct Day9',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task9.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task10',
    name: 'XDF Listening IELTS Intermediate Direct Day10',
    description: 'XDF Listening IELTS Intermediate Direct Day10',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task10.json',
    length: 44,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task11',
    name: 'XDF Listening IELTS Intermediate Direct Day11',
    description: 'XDF Listening IELTS Intermediate Direct Day11',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task11.json',
    length: 36,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task12',
    name: 'XDF Listening IELTS Intermediate Direct Day12',
    description: 'XDF Listening IELTS Intermediate Direct Day12',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task12.json',
    length: 45,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task13',
    name: 'XDF Listening IELTS Intermediate Direct Day13',
    description: 'XDF Listening IELTS Intermediate Direct Day13',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task13.json',
    length: 49,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task14',
    name: 'XDF Listening IELTS Intermediate Direct Day14',
    description: 'XDF Listening IELTS Intermediate Direct Day14',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task14.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task15',
    name: 'XDF Listening IELTS Intermediate Direct Day15',
    description: 'XDF Listening IELTS Intermediate Direct Day15',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task15.json',
    length: 29,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task16',
    name: 'XDF Listening IELTS Intermediate Direct Day16',
    description: 'XDF Listening IELTS Intermediate Direct Day16',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task16.json',
    length: 42,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task17',
    name: 'XDF Listening IELTS Intermediate Direct Day17',
    description: 'XDF Listening IELTS Intermediate Direct Day17',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task17.json',
    length: 22,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task18',
    name: 'XDF Listening IELTS Intermediate Direct Day18',
    description: 'XDF Listening IELTS Intermediate Direct Day18',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task18.json',
    length: 37,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task19',
    name: 'XDF Listening IELTS Intermediate Direct Day19',
    description: 'XDF Listening IELTS Intermediate Direct Day19',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task19.json',
    length: 26,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-1',
    name: 'IELTS Listening Vocabulary 18 Days Day1',
    description: 'IELTS Listening Vocabulary 18 Days Day1',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day1.json',
    length: 74,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-2',
    name: 'IELTS Listening Vocabulary 18 Days Day2',
    description: 'IELTS Listening Vocabulary 18 Days Day2',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day2.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-3',
    name: 'IELTS Listening Vocabulary 18 Days Day3',
    description: 'IELTS Listening Vocabulary 18 Days Day3',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day3.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-4',
    name: 'IELTS Listening Vocabulary 18 Days Day4',
    description: 'IELTS Listening Vocabulary 18 Days Day4',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day4.json',
    length: 73,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-5',
    name: 'IELTS Listening Vocabulary 18 Days Day5',
    description: 'IELTS Listening Vocabulary 18 Days Day5',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day5.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-6',
    name: 'IELTS Listening Vocabulary 18 Days Day6',
    description: 'IELTS Listening Vocabulary 18 Days Day6',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day6.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-7',
    name: 'IELTS Listening Vocabulary 18 Days Day7',
    description: 'IELTS Listening Vocabulary 18 Days Day7',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day7.json',
    length: 75,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-8',
    name: 'IELTS Listening Vocabulary 18 Days Day8',
    description: 'IELTS Listening Vocabulary 18 Days Day8',
    category: 'International Exams',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day8.json',
    length: 75,
    language: 'en',
    languageCategory: 'en',
  },
  {
    "id": "IELTS-listening-18-days-9",
    "name": "IELTS Listening Vocabulary 18 Days - Day 9",
    "description": "IELTS Listening Vocabulary 18 Days - Day 9",
    "category": "International Exams",
    "tags": ["IELTS"],
    "url": "/dicts/IELTS-listening-18days-day9.json",
    "length": 76,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "IELTS-listening-18-days-10",
    "name": "IELTS Listening Vocabulary 18 Days - Day 10",
    "description": "IELTS Listening Vocabulary 18 Days - Day 10",
    "category": "International Exams",
    "tags": ["IELTS"],
    "url": "/dicts/IELTS-listening-18days-day10.json",
    "length": 33,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "IELTS-listening-18-days-11",
    "name": "IELTS Listening Vocabulary 18 Days - Day 11",
    "description": "IELTS Listening Vocabulary 18 Days - Day 11",
    "category": "International Exams",
    "tags": ["IELTS"],
    "url": "/dicts/IELTS-listening-18days-day11.json",
    "length": 52,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "IELTS-listening-18-days-12",
    "name": "IELTS Listening Vocabulary 18 Days - Day 12",
    "description": "IELTS Listening Vocabulary 18 Days - Day 12",
    "category": "International Exams",
    "tags": ["IELTS"],
    "url": "/dicts/IELTS-listening-18days-day12.json",
    "length": 77,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "IELTS-listening-18-days-13",
    "name": "IELTS Listening Vocabulary 18 Days - Day 13",
    "description": "IELTS Listening Vocabulary 18 Days - Day 13",
    "category": "International Exams",
    "tags": ["IELTS"],
    "url": "/dicts/IELTS-listening-18days-day13.json",
    "length": 78,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "IELTS-listening-18-days-14",
    "name": "IELTS Listening Vocabulary 18 Days - Day 14",
    "description": "IELTS Listening Vocabulary 18 Days - Day 14",
    "category": "International Exams",
    "tags": ["IELTS"],
    "url": "/dicts/IELTS-listening-18days-day14.json",
    "length": 76,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "IELTS-listening-18-days-15",
    "name": "IELTS Listening Vocabulary 18 Days - Day 15",
    "description": "IELTS Listening Vocabulary 18 Days - Day 15",
    "category": "International Exams",
    "tags": ["IELTS"],
    "url": "/dicts/IELTS-listening-18days-day15.json",
    "length": 77,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "IELTS-listening-18-days-16",
    "name": "IELTS Listening Vocabulary 18 Days - Day 16",
    "description": "IELTS Listening Vocabulary 18 Days - Day 16",
    "category": "International Exams",
    "tags": ["IELTS"],
    "url": "/dicts/IELTS-listening-18days-day16.json",
    "length": 77,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "IELTS-listening-18-days-17",
    "name": "IELTS Listening Vocabulary 18 Days - Day 17",
    "description": "IELTS Listening Vocabulary 18 Days - Day 17",
    "category": "International Exams",
    "tags": ["IELTS"],
    "url": "/dicts/IELTS-listening-18days-day17.json",
    "length": 46,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "IELTS-listening-18-days-18",
    "name": "IELTS Listening Vocabulary 18 Days - Day 18",
    "description": "IELTS Listening Vocabulary 18 Days - Day 18",
    "category": "International Exams",
    "tags": ["IELTS"],
    "url": "/dicts/IELTS-listening-18days-day18.json",
    "length": 76,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "ket",
    "name": "KET",
    "description": "KET 2021 Vocabulary",
    "category": "International Exams",
    "tags": ["KET"],
    "url": "./dicts/ket2021.json",
    "length": 1147,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "sat",
    "name": "SAT",
    "description": "American SAT Exam Vocabulary",
    "category": "International Exams",
    "tags": ["SAT"],
    "url": "/dicts/SAT_3_T.json",
    "length": 4464,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "SATen",
    "name": "SAT en-en",
    "description": "SAT English-English",
    "category": "International Exams",
    "tags": ["SAT"],
    "url": "/dicts/SATen.json",
    "length": 2681,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "toefl",
    "name": "TOEFL",
    "description": "Common TOEFL Exam Words",
    "category": "International Exams",
    "tags": ["TOEFL"],
    "url": "/dicts/TOEFL_3_T.json",
    "length": 4264,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "bec2",
    "name": "Business English",
    "description": "Common Business English Words",
    "category": "International Exams",
    "tags": ["BEC"],
    "url": "/dicts/BEC_2_T.json",
    "length": 2753,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "bec3",
    "name": "BEC",
    "description": "Common BEC Exam Words",
    "category": "International Exams",
    "tags": ["BEC"],
    "url": "/dicts/BEC_3_T.json",
    "length": 2825,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "PTE_junior",
    "name": "PTE Basic Vocabulary",
    "description": "",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/PTE_junior.json",
    "length": 2651,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "PTE_senior",
    "name": "PTE Advanced Vocabulary",
    "description": "",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/PTE_senior.json",
    "length": 3170,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "PTE_FIB_R_junior",
    "name": "Reading FIB Basic Vocabulary",
    "description": "",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/PTE_FIB_R_junior.json",
    "length": 941,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "PTE_FIB_R_senior",
    "name": "Reading FIB Advanced Vocabulary",
    "description": "",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/PTE_FIB_R_senior.json",
    "length": 1272,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "PTE_WFD",
    "name": "WFD Vocabulary",
    "description": "",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/PTE_WFD.json",
    "length": 1212,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "PTE_FIB_L",
    "name": "Listening FIB Vocabulary",
    "description": "",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/PTE_FIB_L.json",
    "length": 646,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "PTE_Basic_apeuni",
    "name": "PTE Basic Vocabulary xingji",
    "description": "",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/PTE_Basic_apeuni.json",
    "length": 2652,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "PTE_Advanced_apeuni.json",
    "name": "PTE Advanced Vocabulary xingji",
    "description": "",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/PTE_Advanced_apeuni.json",
    "length": 3169,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "PTE_Read_apeuni.json",
    "name": "PTE Reading FIB Vocabulary xingji",
    "description": "",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/PTE_Read_apeuni.json",
    "length": 630,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "PTE_Listening_apeuni.json",
    "name": "PTE Listening FIB Vocabulary xingji",
    "description": "",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/PTE_Listening_apeuni.json",
    "length": 674,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "TOEIC",
    "name": "TOEIC Vocabulary",
    "description": "",
    "category": "International Exams",
    "tags": ["TOEIC"],
    "url": "/dicts/TOEIC.json",
    "length": 1694,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "Duolingo_Vocabulary_B1",
    "name": "Duolingo Leveled Vocabulary B1",
    "description": "Duolingo Leveled Vocabulary B1",
    "category": "International Exams",
    "tags": ["CEFR"],
    "url": "/dicts/Duolingo_Vocabulary_B1.json",
    "length": 801,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "Duolingo_Vocabulary_B2",
    "name": "Duolingo Leveled Vocabulary B2",
    "description": "Duolingo Leveled Vocabulary B2",
    "category": "International Exams",
    "tags": ["CEFR"],
    "url": "/dicts/Duolingo_Vocabulary_B2.json",
    "length": 1423,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "Duolingo_Vocabulary_C1",
    "name": "Duolingo Leveled Vocabulary C1",
    "description": "Duolingo Leveled Vocabulary C1",
    "category": "International Exams",
    "tags": ["CEFR"],
    "url": "/dicts/Duolingo_Vocabulary_C1.json",
    "length": 1314,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "Oxford3000",
    "name": "Oxford 3000 Words",
    "description": "Oxford 3000 Words",
    "category": "International Exams",
    "tags": ["Oxford Edition"],
    "url": "/dicts/Oxford3000.json",
    "length": 1342,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "Oxford5000",
    "name": "Oxford 5000 Words",
    "description": "Oxford 5000 Words",
    "category": "International Exams",
    "tags": ["Oxford Edition"],
    "url": "/dicts/Oxford5000.json",
    "length": 5836,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "voa",
    "name": "VOA Basic Vocabulary",
    "description": "VOA Basic Vocabulary",
    "category": "International Exams",
    "tags": ["Other"],
    "url": "/dicts/voa.json",
    "length": 1505,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "Common-Phrases-PTE-Unofficial",
    "name": "PTE Common Phrases (Unofficial)",
    "description": "PTE Common Phrases",
    "category": "International Exams",
    "tags": ["PTE"],
    "url": "/dicts/Common-Phrases-PTE-Unofficial.json",
    "length": 274,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "Common-Phrases-FCE-Unofficial",
    "name": "FCE Common Phrases (Unofficial)",
    "description": "FCE Common Phrases",
    "category": "International Exams",
    "tags": ["FCE"],
    "url": "/dicts/Common-Phrases-FCE-Unofficial.json",
    "length": 438,
    "language": "en",
    "languageCategory": "en"
  }
]

// Youth English
const childrenEnglish = [
  {
    "id": "gaokao3500",
    "name": "Gaokao 3500 Words",
    "description": "Common Gaokao 3500 Words",
    "category": "Youth English",
    "tags": ["General"],
    "url": "/dicts/GaoKao_3500.json",
    "length": 3893,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "gaokaozhentihexin",
    "name": "Gaokao Past Papers Core High Frequency",
    "description": "Gaokao Past Papers Core High Frequency",
    "category": "Youth English",
    "tags": ["General"],
    "url": "/dicts/GaoKaoZhenTiHeXinGaoPin.json",
    "length": 799,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "gaokao-yuedu-gaopin",
    "name": "Gaokao English Reading High Frequency Vocabulary",
    "description": "Gaokao English Reading High Frequency Vocabulary",
    "category": "Youth English",
    "tags": ["General"],
    "url": "/dicts/gaokao-yuedu-gaopin.json",
    "length": 688,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "zhongkaohexin",
    "name": "Zhongkao Core Words",
    "description": "Zhongkao Core Words",
    "category": "Youth English",
    "tags": ["General"],
    "url": "/dicts/ZhongKaoHeXin.json",
    "length": 2140,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "nce1",
    "name": "New Concept English-1",
    "description": "New Concept English Book 1",
    "category": "Youth English",
    "tags": ["New Concept English"],
    "url": "/dicts/NCE_1.json",
    "length": 900,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "nce2",
    "name": "New Concept English-2",
    "description": "New Concept English Book 2",
    "category": "Youth English",
    "tags": ["New Concept English"],
    "url": "/dicts/NCE_2.json",
    "length": 858,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "nce3",
    "name": "New Concept English-3",
    "description": "New Concept English Book 3",
    "category": "Youth English",
    "tags": ["New Concept English"],
    "url": "/dicts/NCE_3.json",
    "length": 1052,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "nce4",
    "name": "New Concept English-4",
    "description": "New Concept English Book 4",
    "category": "Youth English",
    "tags": ["New Concept English"],
    "url": "/dicts/NCE_4.json",
    "length": 784,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "nce-new-1",
    "name": "New Concept English (New Edition)-1",
    "description": "New Concept English New Edition Book 1",
    "category": "Youth English",
    "tags": ["New Concept English"],
    "url": "/dicts/nce-new-1.json",
    "length": 908,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "nce-new-2",
    "name": "New Concept English (New Edition)-2",
    "description": "New Concept English New Edition Book 2",
    "category": "Youth English",
    "tags": ["New Concept English"],
    "url": "/dicts/nce-new-2.json",
    "length": 862,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "nce-new-3",
    "name": "New Concept English (New Edition)-3",
    "description": "New Concept English New Edition Book 3",
    "category": "Youth English",
    "tags": ["New Concept English"],
    "url": "/dicts/nce-new-3.json",
    "length": 1062,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "nce-new-4",
    "name": "New Concept English (New Edition)-4",
    "description": "New Concept English New Edition Book 4",
    "category": "Youth English",
    "tags": ["New Concept English"],
    "url": "/dicts/nce-new-4.json",
    "length": 793,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "SHjuniormiddleOxford",
    "name": "Shanghai Junior Middle School Oxford Vocabulary",
    "description": "Shanghai Junior Middle School Oxford Vocabulary",
    "category": "Youth English",
    "tags": ["Oxford Edition"],
    "url": "/dicts/OxfordVocabulary_juniorMiddleSH.json",
    "length": 1270,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "san1",
    "name": "Grade 3 Semester 1",
    "description": "PEP Edition Grade 3 Semester 1",
    "category": "Youth English",
    "tags": ["PEP Edition"],
    "url": "/dicts/PEPXiaoXue3_1_T.json",
    "length": 64,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "san2",
    "name": "Grade 3 Semester 2",
    "description": "PEP Edition Grade 3 Semester 2",
    "category": "Youth English",
    "tags": ["PEP Edition"],
    "url": "/dicts/PEPXiaoXue3_2_T.json",
    "length": 72,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "si1",
    "name": "Grade 4 Semester 1",
    "description": "PEP Edition Grade 4 Semester 1",
    "category": "Youth English",
    "tags": ["PEP Edition"],
    "url": "/dicts/PEPXiaoXue4_1_T.json",
    "length": 84,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "si2",
    "name": "Grade 4 Semester 2",
    "description": "PEP Edition Grade 4 Semester 2",
    "category": "Youth English",
    "tags": ["PEP Edition"],
    "url": "/dicts/PEPXiaoXue4_2_T.json",
    "length": 104,
    "language": "en",
    "languageCategory": "en"
  },
  {
    "id": "wu1",
    "name": "Grade 5 Semester 1",
    "description": "PEP Edition Grade 5 Semester 1",
    "category": "Youth English",
    "tags": ["PEP Edition"],
    "url": "/dicts/PEPXiaoXue5_1_T.json",
    "length": 131,
    "language": "en",
    "languageCategory": "en"
  },
  {
  id: 'wu2',
  name: 'Grade 5, Semester 2',
  description: 'PEP Edition Grade 5, Volume 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPXiaoXue5_2_T.json',
  length: 156,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'liu1',
  name: 'Grade 6, Semester 1',
  description: 'PEP Edition Grade 6, Volume 1',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPXiaoXue6_1_T.json',
  length: 130,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'liu2',
  name: 'Grade 6, Semester 2',
  description: 'PEP Edition Grade 6, Volume 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPXiaoXue6_2_T.json',
  length: 108,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-yi1',
  name: 'PEP Edition (New Starting Point) Grade 1, Semester 1',
  description: 'PEP Edition Grade 1, Volume 1',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue1_1_t.json',
  length: 52,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-yi2',
  name: 'PEP Edition (New Starting Point) Grade 1, Semester 2',
  description: 'PEP Edition Grade 1, Volume 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue1_2_t.json',
  length: 45,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-er1',
  name: 'PEP Edition (New Starting Point) Grade 2, Semester 1',
  description: 'PEP Edition Grade 2, Volume 1',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue2_1_t.json',
  length: 54,
  language: 'en',
  languageCategory: 'en',
},

{
  id: 'pep-sl-er2',
  name: 'PEP Edition (New Starting Point) Grade 2, Semester 2',
  description: 'PEP Edition Grade 2, Volume 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue2_2_t.json',
  length: 55,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-san1',
  name: 'PEP Edition (New Starting Point) Grade 3, Semester 1',
  description: 'PEP Edition Grade 3, Volume 1',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue3_1_t.json',
  length: 103,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-san2',
  name: 'PEP Edition (New Starting Point) Grade 3, Semester 2',
  description: 'PEP Edition Grade 3, Volume 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue3_2_t.json',
  length: 84,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-si1',
  name: 'PEP Edition (New Starting Point) Grade 4, Semester 1',
  description: 'PEP Edition Grade 4, Volume 1',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue4_1_t.json',
  length: 115,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-si2',
  name: 'PEP Edition (New Starting Point) Grade 4, Semester 2',
  description: 'PEP Edition Grade 4, Volume 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue4_2_t.json',
  length: 87,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-wu1',
  name: 'PEP Edition (New Starting Point) Grade 5, Semester 1',
  description: 'PEP Edition Grade 5, Volume 1',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue5_1_t.json',
  length: 66,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-wu2',
  name: 'PEP Edition (New Starting Point) Grade 5, Semester 2',
  description: 'PEP Edition Grade 5, Volume 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue5_2_t.json',
  length: 96,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-liu1',
  name: 'PEP Edition (New Starting Point) Grade 6, Semester 1',
  description: 'PEP Edition Grade 6, Volume 1',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue6_1_t.json',
  length: 102,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'pep-sl-liu2',
  name: 'PEP Edition (New Starting Point) Grade 6, Semester 2',
  description: 'PEP Edition Grade 6, Volume 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEP_SL_XiaoXue6_2_t.json',
  length: 41,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'qi1',
  name: 'Grade 7, Semester 1',
  description: 'PEP Edition Grade 7, Volume 1',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPChuZhong7_1_T.json',
  length: 392,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'qi2',
  name: 'Grade 7, Semester 2',
  description: 'PEP Edition Grade 7, Volume 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPChuZhong7_2_T.json',
  length: 492,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'ba1',
  name: 'Grade 8, Semester 1',
  description: 'PEP Edition Grade 8, Volume 1',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPChuZhong8_1_T.json',
  length: 419,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'ba2',
  name: 'Grade 8, Semester 2',
  description: 'PEP Edition Grade 8, Volume 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPChuZhong8_2_T.json',
  length: 466,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jiu',
  name: 'Grade 9',
  description: 'PEP Edition Grade 9 Complete',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPChuZhong9_1_T.json',
  length: 551,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong1',
  name: 'High School Compulsory 1',
  description: 'PEP Edition High School Compulsory 1',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_1_T.json',
  length: 311,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong2',
  name: 'High School Compulsory 2',
  description: 'PEP Edition High School Compulsory 2',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_2_T.json',
  length: 319,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong3',
  name: 'High School Compulsory 3',
  description: 'PEP Edition High School Compulsory 3',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_3_T.json',
  length: 366,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong4',
  name: 'High School Compulsory 4',
  description: 'PEP Edition High School Compulsory 4',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_4_T.json',
  length: 307,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong5',
  name: 'High School Compulsory 5',
  description: 'PEP Edition High School Compulsory 5',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_5_T.json',
  length: 357,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong6',
  name: 'High School Elective 6',
  description: 'PEP Edition High School Elective 6',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_6_T.json',
  length: 391,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong7',
  name: 'High School Elective 7',
  description: 'PEP Edition High School Elective 7',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_7_T.json',
  length: 384,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong8',
  name: 'High School Elective 8',
  description: 'PEP Edition High School Elective 8',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_8_T.json',
  length: 420,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong9',
  name: 'High School Elective 9',
  description: 'PEP Edition High School Elective 9',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_9_T.json',
  length: 352,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong10',
  name: 'High School Elective 10',
  description: 'PEP Edition High School Elective 10',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_10_T.json',
  length: 361,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'renjiaogaozhong11',
  name: 'High School Elective 11',
  description: 'PEP Edition High School Elective 11',
  category: 'Youth English',
  tags: ['PEP Edition'],
  url: '/dicts/PEPGaoZhong_11_T.json',
  length: 309,
  language: 'en',
  languageCategory: 'en',
},

{
  id: 'waiyan1',
  name: 'Foreign Language Teaching Grade 7, Volume 1',
  description: 'FLTRP Edition Grade 7, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_1_T.json',
  length: 629,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'new-waiyan1',
  name: 'New FLTRP Grade 7, Volume 1',
  description: 'New FLTRP Edition Grade 7, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/Newwaiyan7-1.json',
  length: 294,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'new-waiyan2',
  name: 'New FLTRP Grade 7, Volume 2',
  description: 'New FLTRP Edition Grade 7, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/Newwaiyan7-2.json',
  length: 305,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan2',
  name: 'Foreign Language Teaching Grade 7, Volume 2',
  description: 'FLTRP Edition Grade 7, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_2_T.json',
  length: 438,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan3',
  name: 'Foreign Language Teaching Grade 8, Volume 1',
  description: 'FLTRP Edition Grade 8, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_3_T.json',
  length: 320,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan4',
  name: 'Foreign Language Teaching Grade 8, Volume 2',
  description: 'FLTRP Edition Grade 8, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_4_T.json',
  length: 266,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan5',
  name: 'Foreign Language Teaching Grade 9, Volume 1',
  description: 'FLTRP Edition Grade 9, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_5_T.json',
  length: 381,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan6',
  name: 'Foreign Language Teaching Grade 9, Volume 2',
  description: 'FLTRP Edition Grade 9, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_6_T.json',
  length: 128,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan7',
  name: 'Foreign Language Teaching High School Compulsory 1',
  description: 'FLTRP High School Compulsory 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheGaoZhong_1_T.json',
  length: 411,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan8',
  name: 'Foreign Language Teaching High School Compulsory 2',
  description: 'FLTRP High School Compulsory 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheGaoZhong_2_T.json',
  length: 272,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan9',
  name: 'Foreign Language Teaching Grade 1, Volume 1',
  description: 'FLTRP Grade 1, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_1-Volume-up.json',
  length: 138,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan10',
  name: 'Foreign Language Teaching Grade 1, Volume 2',
  description: 'FLTRP Grade 1, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_1-Volume-down.json',
  length: 118,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan11',
  name: 'Foreign Language Teaching Grade 2, Volume 1',
  description: 'FLTRP Grade 2, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_2-Volume-top.json',
  length: 118,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan12',
  name: 'Foreign Language Teaching Grade 2, Volume 2',
  description: 'FLTRP Grade 2, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_2-Volume-down.json',
  length: 110,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan13',
  name: 'Foreign Language Teaching Grade 3, Volume 1',
  description: 'FLTRP Grade 3, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_3-Volume-top.json',
  length: 82,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan14',
  name: 'Foreign Language Teaching Grade 3, Volume 2',
  description: 'FLTRP Grade 3, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_3-Volume-down.json',
  length: 106,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan15',
  name: 'Foreign Language Teaching Grade 4, Volume 1',
  description: 'FLTRP Grade 4, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_4-Volume-top.json',
  length: 116,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan16',
  name: 'Foreign Language Teaching Grade 4, Volume 2',
  description: 'FLTRP Grade 4, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_4-Volume-down.json',
  length: 78,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan17',
  name: 'Foreign Language Teaching Grade 5, Volume 1',
  description: 'FLTRP Grade 5, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_5-Volume-top.json',
  length: 80,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan18',
  name: 'Foreign Language Teaching Grade 5, Volume 2',
  description: 'FLTRP Grade 5, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_5-Volume-down.json',
  length: 72,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan19',
  name: 'Foreign Language Teaching Grade 6, Volume 1',
  description: 'FLTRP Grade 6, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_6-Volume-top.json',
  length: 61,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan20',
  name: 'Foreign Language Teaching Grade 6, Volume 2',
  description: 'FLTRP Grade 6, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/WaiYanSheChuZhong_6-Volume-down.json',
  length: 91,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan3-1',
  name: 'FLTRP New Starting Point Grade 3, Volume 1',
  description: 'FLTRP New Starting Point Grade 3, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/waiyan-xin-3-1.json',
  length: 134,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan3-2',
  name: 'FLTRP New Starting Point Grade 3, Volume 2',
  description: 'FLTRP New Starting Point Grade 3, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/waiyan-xin-3-2.json',
  length: 156,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan4-1',
  name: 'FLTRP New Starting Point Grade 4, Volume 1',
  description: 'FLTRP New Starting Point Grade 4, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/waiyan-xin-4-1.json',
  length: 144,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan4-2',
  name: 'FLTRP New Starting Point Grade 4, Volume 2',
  description: 'FLTRP New Starting Point Grade 4, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/waiyan-xin-4-2.json',
  length: 134,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan5-1',
  name: 'FLTRP New Starting Point Grade 5, Volume 1',
  description: 'FLTRP New Starting Point Grade 5, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/waiyan-xin-5-1.json',
  length: 152,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan5-2',
  name: 'FLTRP New Starting Point Grade 5, Volume 2',
  description: 'FLTRP New Starting Point Grade 5, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/waiyan-xin-5-2.json',
  length: 147,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan6-1',
  name: 'FLTRP New Starting Point Grade 6, Volume 1',
  description: 'FLTRP New Starting Point Grade 6, Volume 1',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/waiyan-xin-6-1.json',
  length: 83,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'waiyan6-2',
  name: 'FLTRP New Starting Point Grade 6, Volume 2',
  description: 'FLTRP New Starting Point Grade 6, Volume 2',
  category: 'Youth English',
  tags: ['FLTRP Edition'],
  url: '/dicts/waiyan-xin-6-2.json',
  length: 105,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'shanghai-6-2word',
  name: 'Shanghai New Textbook Grade 6, Volume 2',
  description: 'Shanghai New Textbook Grade 6, Volume 2',
  category: 'Youth English',
  tags: ['Shanghai Edition'],
  url: '/dicts/shanghai-6-2-word.json',
  length: 274,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'Yilin1',
  name: 'High School Compulsory 1',
  description: 'Yilin Edition High School Compulsory 1',
  category: 'Youth English',
  tags: ['Yilin Edition'],
  url: './dicts/YiLin_1.json',
  length: 276,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'Yilin2',
  name: 'High School Compulsory 2',
  description: 'Yilin Edition High School Compulsory 2',
  category: 'Youth English',
  tags: ['Yilin Edition'],
  url: './dicts/YiLin_2.json',
  length: 297,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'Yilin3',
  name: 'High School Compulsory 3',
  description: 'Yilin Edition High School Compulsory 3',
  category: 'Youth English',
  tags: ['Yilin Edition'],
  url: './dicts/YiLin_3.json',
  length: 295,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi1',
  name: 'High School Compulsory 1',
  description: 'Beijing Normal University Edition High School Compulsory 1',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_1_T.json',
  length: 226,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi2',
  name: 'High School Compulsory 2',
  description: 'Beijing Normal University Edition High School Compulsory 2',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_2_T.json',
  length: 244,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi3',
  name: 'High School Compulsory 3',
  description: 'Beijing Normal University Edition High School Compulsory 3',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_3_T.json',
  length: 295,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi4',
  name: 'High School Compulsory 4',
  description: 'Beijing Normal University Edition High School Compulsory 4',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_4_T.json',
  length: 336,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi5',
  name: 'High School Compulsory 5',
  description: 'Beijing Normal University Edition High School Compulsory 5',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_5_T.json',
  length: 327,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi6',
  name: 'High School Elective 6',
  description: 'Beijing Normal University Edition High School Elective 6',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_6_T.json',
  length: 271,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi7',
  name: 'High School Elective 7',
  description: 'Beijing Normal University Edition High School Elective 7',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_7_T.json',
  length: 334,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi8',
  name: 'High School Elective 8',
  description: 'Beijing Normal University Edition High School Elective 8',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_8_T.json',
  length: 364,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi9',
  name: 'High School Elective 9',
  description: 'Beijing Normal University Edition High School Elective 9',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_9_T.json',
  length: 299,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi10',
  name: 'High School Elective 10',
  description: 'Beijing Normal University Edition High School Elective 10',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_10_T.json',
  length: 267,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'beishi11',
  name: 'High School Elective 11',
  description: 'Beijing Normal University Edition High School Elective 11',
  category: 'Youth English',
  tags: ['BNU'],
  url: '/dicts/BeiShiGaoZhong_11_T.json',
  length: 330,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao1',
  name: 'Jijiao Grade 3, Volume 1',
  description: 'Hebei Education Edition Grade 3 Starting Point, Volume 1',
  category: 'Youth English',
  tags: ['Hebei Education Edition'],
  url: '/dicts/jiJiao3-1.json',
  length: 75,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao2',
  name: 'Jijiao Grade 3, Volume 2',
  description: 'Hebei Education Edition Grade 3 Starting Point, Volume 2',
  category: 'Youth English',
  tags: ['Hebei Education Edition'],
  url: '/dicts/jiJiao3-2.json',
  length: 76,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao3',
  name: 'Jijiao Grade 4, Volume 1',
  description: 'Hebei Education Edition Grade 3 Starting Point, Grade 4, Volume 1',
  category: 'Youth English',
  tags: ['Hebei Education Edition'],
  url: '/dicts/jiJiao4-1.json',
  length: 78,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao4',
  name: 'Jijiao Grade 4, Volume 2',
  description: 'Hebei Education Edition Grade 3 Starting Point, Grade 4, Volume 2',
  category: 'Youth English',
  tags: ['Hebei Education Edition'],
  url: '/dicts/jiJiao4-2.json',
  length: 84,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao5',
  name: 'Jijiao Grade 5, Volume 1',
  description: 'Hebei Education Edition Grade 3 Starting Point, Grade 5, Volume 1',
  category: 'Youth English',
  tags: ['Hebei Education Edition'],
  url: '/dicts/jiJiao5-1.json',
  length: 79,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao6',
  name: 'Jijiao Grade 5, Volume 2',
  description: 'Hebei Education Edition Grade 3 Starting Point, Grade 5, Volume 2',
  category: 'Youth English',
  tags: ['Hebei Education Edition'],
  url: '/dicts/jiJiao5-2.json',
  length: 96,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao7',
  name: 'Jijiao Grade 6, Volume 1',
  description: 'Hebei Education Edition Grade 3 Starting Point, Grade 6, Volume 1',
  category: 'Youth English',
  tags: ['Hebei Education Edition'],
  url: '/dicts/jiJiao6-1.json',
  length: 66,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao8',
  name: 'Jijiao Grade 6, Volume 2',
  description: 'Hebei Education Edition Grade 3 Starting Point, Grade 6, Volume 2',
  category: 'Youth English',
  tags: ['Hebei Education Edition'],
  url: '/dicts/jiJiao6-2.json',
  length: 51,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao9',
  name: 'Jijiao Grade 7, Volume 1',
  description: 'Hebei Education Edition Grade 3 Starting Point, Grade 7, Volume 1',
  category: 'Youth English',
  tags: ['Hebei Education Edition'],
  url: '/dicts/jiJiao7-1.json',
  length: 561,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao10',
  name: 'Jijiao Grade 7, Volume 2',
  description: 'Hebei Education Edition Grade 3 Starting Point, Grade 7, Volume 2',
  category: 'Youth English',
  tags: ['Hebei Education Edition'],
  url: '/dicts/jiJiao7-2.json',
  length: 514,
  language: 'en',
  languageCategory: 'en',
},
  {
  id: 'jijiao11',
  name: 'JiJiao Grade 8 Semester 1',
  description: 'Hebei Education Press Edition, Starting from Grade 3, Grade 8 Semester 1',
  category: 'Teen English',
  tags: ['Hebei Education Press'],
  url: '/dicts/jiJiao8-1.json',
  length: 420,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao12',
  name: 'JiJiao Grade 8 Semester 2',
  description: 'Hebei Education Press Edition, Starting from Grade 3, Grade 8 Semester 2',
  category: 'Teen English',
  tags: ['Hebei Education Press'],
  url: '/dicts/jiJiao8-2.json',
  length: 487,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'jijiao13',
  name: 'JiJiao Grade 9 Full Book',
  description: 'Hebei Education Press Edition, Starting from Grade 3, Grade 9 Complete Book',
  category: 'Teen English',
  tags: ['Hebei Education Press'],
  url: '/dicts/jiJiao9.json',
  length: 636,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'BJJuniorHigh',
  name: 'Beijing Junior High',
  description: 'Beijing Junior High School English',
  category: 'Teen English',
  tags: ['Others'],
  url: '/dicts/beijing_junior_high_school.json',
  length: 1844,
  language: 'en',
  languageCategory: 'en',
},

//Reading Explorer Series
{
  id: 'ReadingExplorer3',
  name: 'Reading Explorer 3',
  description: 'Vocabulary list from Reading Explorer 3, Third Edition',
  category: 'Teen English',
  tags: ['Others'],
  url: '/dicts/ReadingExplorer3.json',
  length: 239,
  language: 'en',
  languageCategory: 'en',
},
{
  id: 'Cambridge_JOIN_IN',
  name: 'Cambridge Primary English JOIN IN',
  description: 'An English textbook series jointly developed by Foreign Language Teaching and Research Press and Cambridge University Press for Chinese primary school students, based on the requirements of the "Compulsory Education English Curriculum Standards".',
  category: 'Teen English',
  tags: ['Others'],
  url: '/dicts/Cambridge_JOIN_IN.json',
  length: 1350,
  language: 'en',
  languageCategory: 'en',
},
]


function start(list, name) {
  list.map(v => {
    let s = v.url.replace('./dicts/', '')
    s = s.replace('/dicts/', '')
    const sourcePath = path.join(SOURCE_DIR, s);
    // Check if the file exists
    if (fs.existsSync(sourcePath)) {
      const raw = JSON.parse(fs.readFileSync(sourcePath, 'utf-8'));
      if (v.length !== raw.length) {
        console.log(v.name, v.length, raw.length)
      }
    } else {
      console.warn(`File not found: ${s}`);
    }
  })
}

start(chinaExam, 'chinaExam')
start(internationalExam, 'internationalExam')
start(childrenEnglish, 'childrenEnglish')
