version: "2"
services:
  typeword:
    image: "node:latest"
    # environment: # Configurar si es necesario, principalmente para resolver problemas de red al instalar dependencias (proxy)
    #   - HTTP_PROXY=http://127.0.0.1:80
    #     HTTPS_PROXY=http://127.0.0.1:80
    working_dir: /home/node/app
    volumes: # Mapear directamente el directorio del código al contenedor, ahorrando tiempo de empaquetado y copia
      - ./:/home/node/app
    expose:
      - "3000"
    ports: 
      - "3000:3000"
    command: 
      - /bin/bash
      - -c
      - |
          npm install
          npm start
